[chore] add tests for Java auto-instrumentation
signalfx/splunk-otel-collector-chart pull request #1131
Opened 2024-01-26 08:50 UTC by atoulme

**Description:**
Add tests with Apache Tomcat, sending spans every second.

2024-01-26 15:38 UTC, jvoravong commented on functional_tests/testdata/java/Makefile
> +
```suggestion
```

2024-01-26 15:38 UTC, jvoravong commented on functional_tests/testdata/java/README.md
> +# Node.js test image
```suggestion
# Java test image
```

2024-01-26 15:39 UTC, jvoravong approved these changes

2024-01-26 15:53 UTC, jvoravong commented
I thought the test failures were just random, turns out they are reproducible. We'll have to fix these tests first.

2024-01-26 15:54 UTC, jvoravong requested changes
I thought the test failures were just random, turns out they are reproducible. We'll have to fix these tests first.

2024-01-26 16:06 UTC, atoulme commented
> I thought the test failures were just random, turns out they are reproducible. We'll have to fix these tests first.

Working on it

2024-01-26 17:04 UTC, atoulme commented
I have found that the docker image for java was not in a public repository, fixing that. Trying.

2024-01-29 17:05 UTC, jvoravong approved these changes

2024-01-29 23:20 UTC, jinja2 approved these changes

2024-02-06 00:04 UTC, merged