Adding pprof extension
signalfx/splunk-otel-collector-chart pull request #500
Opened 2022-07-26 13:45 UTC by ypatel-crest

Adding Prof extension

Testing:

- Check with nordport and headless. 
- Check with enabled and disabled pprof.
- Check with multiple nodes.

2022-07-28 06:30 UTC, ypatel-crest commented on helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl
> +  pprof:
Yes, I have changed it.

2022-07-28 17:40 UTC, dmitryax requested changes
As @rmfitzpatrick mentioned, it's already possible to enable pprof with the following config:

```yaml
agent:
  config:
    extensions:
      pprof:
    service:
      extensions:
        - file_storage
        - health_check
        - k8s_observer
        - memory_ballast
        - zpages
        - pprof
```

The values.yaml is already complicated a lot. We don't want to add this kind of configuration for every config customization use case

2022-07-28 17:41 UTC, dmitryax commented
I'd would say let's add it in https://github.com/signalfx/splunk-otel-collector-chart/blob/main/examples instead

2022-07-29 07:48 UTC, ypatel-crest commented
> I'd would say let's add it in https://github.com/signalfx/splunk-otel-collector-chart/blob/main/examples instead

Yes, I have created a new file in  /example.

2022-08-01 17:17 UTC, dmitryax approved these changes

2022-08-02 13:14 UTC, merged