Add changes to SCK migration doc after testing migration scenario
signalfx/splunk-otel-collector-chart pull request #605
Opened 2022-12-13 13:41 UTC by aryznar-splunk

2022-12-13 14:52 UTC, jvoravong approved these changes

2022-12-14 08:12 UTC, harshit-splunk requested changes

2022-12-14 08:12 UTC, harshit-splunk commented on docs/migration-from-sck.md
> +Splunk Connect for Kubernetes define `sourcetype` for containers as `kube:<container_name>`
By default, SCK defines `sourcetype` for containers as `kube:container:<container_name>`. It explicitly defines 
`sourcetype` as `kube:<container_name>` for Kubernetes core components(i.e. kubelet, etcd, API server etc).
It is also configurable here: https://github.com/splunk/splunk-connect-for-kubernetes/blob/2cae9b12bbd6545c9ef09b23e619b9783d9ceb38/helm-chart/splunk-connect-for-kubernetes/values.yaml#L359

2022-12-14 13:18 UTC, harshit-splunk requested changes

2022-12-14 13:18 UTC, harshit-splunk commented on docs/migration-from-sck.md
> +Splunk OpenTelemetry Collector for Kubernetes by defualt define `sourcetype` for containers as `kube:container:<container_name>`. `sourcetype` configuration can be change in `values.yaml` configurati
```suggestion
Both Splunk Connect for Kubernetes and Splunk OpenTelemetry Collector for Kubernetes define `sourcetype` for container logs as `kube:container:<container_name>` by default. But, Splunk Connect for Kubernetes explicitly defines the sourcetype of Kubernetes core components as `kube:<container_name>`. They are defined [here](https://github.com/splunk/splunk-connect-for-kubernetes/blob/2cae9b12bbd6545c9ef09b23e619b9783d9ceb38/helm-chart/splunk-connect-for-kubernetes/values.yaml#L330-L408)
`sourcetype` configuration can be changed by adding `logsCollection.containers.extraOperators` configuration.
```

You can also add an example:
```yaml
logsCollection:
  containers:
    extraOperators:
    - type: add
       if: resource["k8s.container.name"] == "kube-apiserver"
       field: resource["com.splunk.sourcetype"]
       value: EXPR("kube:"+resource["k8s.container.name"])
```
It renames sourcetype for kube-apiserver.

2022-12-15 08:48 UTC, harshit-splunk approved these changes

2022-12-15 10:18 UTC, merged