Add deployment.environment to metrics always instead of just when splunkPlatform metrics are enabled
signalfx/splunk-otel-collector-chart pull request #791
Opened 2023-05-22 17:06 UTC by rjduffner

2023-05-23 13:42 UTC, jvoravong commented
Hey @rjduffner,
Thanks for contributing. This change looks valid to make our chart usage more uniform. Could you apply the same change to these other locations and add a CHANGELOG.md entry?
- https://github.com/signalfx/splunk-otel-collector-chart/blob/eb4ba48bad7bfa90a7442f43d276c7567f2f9072/helm-charts/splunk-otel-collector/templates/config/_otel-collector.tpl#L222
- https://github.com/signalfx/splunk-otel-collector-chart/blob/eb4ba48bad7bfa90a7442f43d276c7567f2f9072/helm-charts/splunk-otel-collector/templates/config/_otel-k8s-cluster-receiver-config.tpl#L150

2023-05-23 13:44 UTC, jvoravong commented
You will need to run [make render](https://github.com/signalfx/splunk-otel-collector-chart/blob/eb4ba48bad7bfa90a7442f43d276c7567f2f9072/Makefile#L1) on your local machine so the rendered examples are updated with your changes and for the pre-commit action to to pass.

2023-05-23 21:51 UTC, dmitryax requested changes
This is done intentionally. `deployment.environment` is used for tracing and logs. Splunk Observability uses `sf_environment` for metrics which is set from the [trace correlation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter) which at the end must be the same value. So if you're using APM product, it should be already there. If you don't use the APM product, can you please share more details on how you use this attribute?

If we decide to make this change, it requires thorough testing before applying. It might introduce some issue for Splunk Observability.

2023-05-23 21:52 UTC, dmitryax commented
More context from the git blame https://github.com/signalfx/splunk-otel-collector-chart/pull/399

2023-05-24 18:35 UTC, rjduffner commented
Thanks for the tips there @jvoravong. Will update those.

@dmitryax, We need a way to correlate infra metrics coming off each host to a specific environment.

Yes APM metrics are working with sf_environment and traces are working with deployment.environment. What is missing is attributes from receivers like hostmetrics or k8s metrics. While we can filter based on cluster name, it would be nice to also have the environment since we do put it in that values file.

Maybe I am missing something though. Thanks!

2023-05-24 20:02 UTC, dmitryax commented
> Yes APM metrics are working with sf_environment and traces are working with deployment.environment. What is missing is attributes from receivers like hostmetrics or k8s metrics. While we can filter based on cluster name, it would be nice to also have the environment since we do put it in that values file.

All the metrics, including hostmetrics or k8s metrics, should have `sf_environment` as long as they are sent via `signalfx` exporter and the traces pipeline has `signalfx` exporter as well. See https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter#traces-configuration-correlation-only for more details

2023-05-24 22:19 UTC, rjduffner commented
Hi @dmitryax, I have the signalfx exporter and checked the metric cpu.utilization.

I can see it contains the dimension, k8s.cluster.name (added here: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl#L555) but we do not have sf_environment.

Also note, we are using the exporter as default in the chart and only passing in our token through the values file.

2023-05-24 22:44 UTC, dmitryax commented
@rjduffner `sf_environment` is sent as a property, not a dimension. You can use properties the same way as dimensions, but they are not visible in the data table. You should be able to see it in the metrics finder https://app.signalfx.com/#/metrics/?query=cpu.utilization

<img width="1252" alt="Screenshot 2023-05-24 at 3 42 42 PM" src="https://github.com/signalfx/splunk-otel-collector-chart/assets/6628631/37df2f49-ece9-4b6d-9b3d-96a4b4965927">

2023-05-25 16:54 UTC, rjduffner commented
Ok thanks for the information. Its a bit strange its not in the data table as it makes discoverability very hard as well as monitoring multiple envs at once... tricky to say the least.

But good to know its there. Thanks for the help.

2023-05-25 16:54 UTC, closed without merging